import{i as u,S as p}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const a=document.querySelector(".form"),f=document.querySelector(".gallery"),l=document.querySelector(".loader");function m(){l.classList.remove("hidden")}function c(){l.classList.add("hidden")}a.addEventListener("submit",d);function d(n){n.preventDefault();const r=n.target.elements.input.value,s="42276910-5dbc0617c597b0712888fd711";if(r==="")return u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});m(),h(s,r).then(t=>{g(t),c()}).catch(t=>{console.error("Error fetching photos:",t),c()}).finally(()=>a.reset())}function h(n,r){const s="https://pixabay.com",t="/api/",e=`?key=${n}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`,o=s+t+e;return fetch(o).then(i=>i.json())}function g(n){const r=n.hits.map(t=>`<li class="gallery-item">
             <a class="gallery-link" href="${t.webformatURL}">
            <img class="gallery-image" src="${t.largeImageURL}" alt="${t.tags}" />
            </a>
            <p><b>Likes: </b>${t.likes}</p>
            <p><b>Views: </b>${t.views}</p>
            <p><b>Comments: </b>${t.comments}</p> 
            <p><b>Downloads: </b>${t.downloads}</p>
        </li>`).join("");f.insertAdjacentHTML("afterbegin",r);const s=new p(".gallery a",y);s.refresh(),s.on("show.simplelightbox")}const y={captions:!0,captionType:"attr",captionSelector:"img",captionsData:"alt",captionPosition:"bottom",captionDelay:250};
//# sourceMappingURL=commonHelpers.js.map
